### ISSUE TITLE
Parsing URI "relative references"

### ISSUE THREAD

**Issue by secretfader** [g1eny0ung/parse_link_header#1]
I tried parsing responses from a server that uses [relative references](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link) [in the `Link` header](https://webmention.rocks/test/1), which unfortunately failed. As I understand the HTTP specification, this behavior [is supported](https://tools.ietf.org/html/rfc3986#section-4.1). Maybe we can try parsing values into `http::Uri`s instead?

Since parsing the header value into a URI may also fail, I think it's sensible for this library to return `Option<HashMap>`. Or, if we want to explain why an operation failed, `Result<HashMap>` (my preference, since it lets the caller decide what to ignore).

However, these changes would require a version bump and significantly change the project as it stands today, possibly expanding it beyond the scope of features that are personally useful.

Would you be open to changes like I mentioned above? (Either way is fine, I just want to avoid duplicating work.)

**Comment by g1eny0ung** [comment]
@secretfader Thx for the advice! It's really helpful!

> I tried parsing responses from a server that uses relative references in the Link header. As I understand the HTTP specification, this behavior is supported. Maybe we can try parsing values into `http::Uri`s instead?

if I understand correctly, `http::Uri` refers from https://docs.rs/http/0.2.1/http/uri/index.html. To be honest, this library was developed for a project in the company I work for, so I only use it to handle the pagination of GitHub API. I agree with u, I should also follow the HTTP specification to handle the relative ref.

> Since parsing the header value into a URI may also fail, I think it's sensible for this library to return Option<HashMap>. Or, if we want to explain why an operation failed, Result<HashMap> (my preference, since it lets the caller decide what to ignore).

I also think about what exactly to use as the return value. Maybe define a struct is the best choice? For example:

```rust
pub struct LinkValue {
    pub uri: Uri, // as you mentioned, parsing link into http::Uri
    pub raw_uri: String, // the original link string
    pub params: HashMap<String, String>, // params map
}
```

Then wrap into an enum: 

```rust
pub enum Link {
    Rel(Option<String>),
    Value(LinkValue),
}
```

At last, the `parse` function's definition is:

```rust
fn parse(link_header: &str) -> Result<HashMap<Link::Rel, Link::Value>>
```

I'm going to modify it like this if you think it's okay?

**Comment by g1eny0ung** [comment]
@secretfader Thx for the advice! It's really helpful!

> I tried parsing responses from a server that uses relative references in the Link header. As I understand the HTTP specification, this behavior is supported. Maybe we can try parsing values into `http::Uri`s instead?

if I understand correctly, `http::Uri` refers from https://docs.rs/http/0.2.1/http/uri/index.html. To be honest, this library was developed for a project in the company I work for, so I only use it to handle the pagination of GitHub API. I agree with u, I should also follow the HTTP specification to handle the relative ref.

> Since parsing the header value into a URI may also fail, I think it's sensible for this library to return Option<HashMap>. Or, if we want to explain why an operation failed, Result<HashMap> (my preference, since it lets the caller decide what to ignore).

I also think about what exactly to use as the return value. Maybe define a struct is the best choice? For example:

```rust
#[derive(Debug, PartialEq)]
pub struct Link {
    pub uri: Uri, // as you mentioned, parsing link into http::Uri
    pub raw_uri: String, // the original link string
    pub params: HashMap<String, String>, // params map
}

type Rel = String;
```

Then the `parse` function's definition is:

```rust
fn parse(link_header: &str) -> Result<HashMap<Option<Rel>, Link>, &'static str>
```

I'm going to modify it like this if you think it's okay?

**Comment by secretfader** [comment]
@g1eny0ung Thanks for your prompt response, and willingness to investigate changes. :)

> if I understand correctly, `http::Uri` refers from https://docs.rs/http/0.2.1/http/uri/index.html. To be honest, this library was developed for a project in the company I work for, so I only use it to handle the pagination of GitHub API. I agree with u, I should also follow the HTTP specification to handle the relative ref.

You're totally correct. I've tried parsing the `href` value as a URI, which worked using [`TryFrom`](https://docs.rs/http/0.2.1/http/uri/struct.Uri.html#method.try_from). I haven't found a solution to neatly split off query pairs (like the current library) yet.

While I think the above representation (struct of `Link`) makes sense, I don't need to store the raw `String` for my purposes. Ensuring that the URI parses successfully is fine, unless you need the raw string representation for your needs.

**Comment by g1eny0ung** [comment]
@secretfader https://github.com/g1eny0ung/parse_link_header/commit/d1afa7a5d4dd2978f47808f029fb6e3992f73cd1

The new implementation is out.

Finally, I choose to panic when an error occurs in URL parsing. Because I think if the URL is wrong, the Link Header is also meaningless.

And I also add the `queries` key into `Link` struct.

Now the definitions are:

```rust
#[derive(Debug, PartialEq)]
pub struct Link {
    pub uri: Uri,
    pub raw_uri: String,
    pub queries: HashMap<String, String>,
    pub params: HashMap<String, String>,
}

type Rel = String;

fn parse(link_header: &str) -> Result<HashMap<Option<Rel>, Link>, ()>
```

If there is no problem, I will release version `0.2`.

**Comment by secretfader** [comment]
That implementation looks good, although my expectation is that libraries shouldn't panic except as a last resort.

My usage is a [Webmention client and support library for Rust](https://github.com/secretfader/webmention-rs), which I expect will encounter all forms of bad data (and hopefully, recover elegantly). For now, I'll close this issue and likely tinker with an implementation that can be contributed once I've cleaned up the bugs (which the Webmention conformance suite will probably shake out).

**Comment by g1eny0ung** [comment]
Alright. I will first release version 0.2 to fix the relative ref problem. Thank you very much for your help!
