### ISSUE TITLE
Release `v0.2.3` or `v0.3.0`

### ISSUE THREAD

**Issue by g1eny0ung** [g1eny0ung/parse_link_header#12]
After #5, #9, #10, #11 merged, we should release a new version and publish the package to crates.

@mdharm Do you think we should bump the `minor` version? Or just bump the `patch` version.

I prefer to bump the `minor` version (to `v0.3.0`) to tell users that we have made great improvements and optimizations even though there has been no actual usage impact.

**Comment by mdharm** [comment]
Since there is significant new functionality (including both a new feature and a new function call), I suggest bumping the `minor` version.

**Comment by g1eny0ung** [comment]
I will release it right now.

And I also invited u to access this repo as a collaborator. Thank you very much again for your contributes. ❤️

**Comment by mdharm** [comment]
I see the release on [crates.io](https://crates.io/crates/parse_link_header), and I have accepted your invitation to become a collaborator on this project.  Closing this issue.
