### ISSUE TITLE
parse_link_header panics instead of returning `Err(E)`

### ISSUE THREAD

**Issue by mdharm** [g1eny0ung/parse_link_header#3]
The current implementation panics instead of returning an `Err(E)`, even though the signature of the function is a `Result<T, E>`.  If it returned an `E` that implemented the trait `std::error::Error`, then error handling would be easier and this could be used with other crates such as `anyhow`.

I am willing to make some patches to do this, if the project is being actively maintained and the patches would be accepted.

**Comment by g1eny0ung** [comment]
> The current implementation panics instead of returning an `Err(E)`, even though the signature of the function is a `Result<T, E>`. If it returned an `E` that implemented the trait `std::error::Error`, then error handling would be easier and this could be used with other crates such as `anyhow`.
> 
> I am willing to make some patches to do this, if the project is being actively maintained and the patches would be accepted.

Great! Thank you for finding this issue and if you have free time, PR is welcome.
